#!/usr/bin/env bash
#Script that installs and configures HAProxy on IB-01 server with
# a roundrobin algorithm
# and its  management via init script enabled

sudo apt -get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend johnharry-frontend
	bind *:80
	mode http
	default_backend johnharry-backend
backend johnharry-backnd
	balance roundrobin
	server 499430-web-01 3.86.13.91:80 check
	server 499430-web-02 54.173.199.160:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
