#!/usr/bin/env bash
# installs Nginx with the stipulated guidelines
apt-get update 
apt-get install -y nginx

ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html

service nginx restart
