#!/usr/bin/env bash
#script that is used for ubuntu server configuration

sudo apt-get update
sudo apt-get install -y nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html
rep_string="server_name _;\n\trewrite ^\/redirect_me http:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$rep_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
rep_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$rep_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
