#!/usr/bin/env bash
# creates the file /var/run/myscript.pid holding its PID
# displayes To infinity and beyond indefinitelyi

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit'  SIGTERM
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
