#!/usr/bin/env bash
# Script that checks out the existence of a file

fi="school"
if [ -e "$fi" ]
then
	echo "school file exists"
	if [ ! -s "$fi" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$fi" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
