#!/usr/bin/env bash
# script that changes localhost IP and facebook IP
cp /etc/hosts ~/new_host_ip
sed -i 's/127.0.0.1/127.0.0.2/' ~/new_host_ip
sed -i '2i8.8.8.8 facebook.com' ~/new_host_ip
cp -f ~/new_host_ip /etc/hosts
rm -f ~/new_host_ip
