#!/usr/bin/env bash
# Displays Best School with exception of 4th and 8th iteration

rec=10
while [ $rec -gt 0 ]
do 
	if [ $rec = 3 ]
	then
		echo "good luck"
	elif [ $rec = 7 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((rec=rec-1))
done

